### ISSUE TITLE
GCE provider

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/sp19-516-132#1]
is your provider working to start and manage VMS?

I started making a simple mod to 

cloudmesh.compute.libcloud.Provider 

and adde 5 lines of code that were inspired from your current work. Are there more changes?
taht we ned to pull into the libcloud Provider?

**Comment by himanshu3jul** [comment]
We are able to perform following tasks
a. Create VM
b. Stop VM
c. Start VM
d. Destroy VM
e. SSH into VM
f. List VMs (Having issue with formatting the output)
