### ISSUE TITLE
mongo

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/sp19-516-132#2]
I see:

https://github.com/cloudmesh-community/sp19-516-132/blob/master/section-code/cloudmesh.mongo/MongoDBController.py

was this or will this be integrated into mongo?

we may want to remove this if this is already in cm and just use pull requests and delete this and update your readme.yaml file.
you can discuss with me in online hour

**Comment by himanshu3jul** [comment]
Yes. This is already integrated with CM. I will remove this content from my repo and just mention the pull requests.
