### ISSUE TITLE
we need to integrate this into cloudmesh-cloud

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/sp19-516-132#4]

**Comment by himanshu3jul** [comment]
We have already integrated this to the cloudmesh-cloud
a. google test
b. VM API
c. Libcloud

**Comment by laszewsk** [comment]
Great!

**Comment by laszewsk** [comment]
have you taken a liook at my suggestions for improving the tests, it explcitly shoudl test recursive directory uploads
